version: '3.0'

services:
  scrap-words:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run scrap
  scrap-definitions:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run scrap-definitions
  parse-definitions:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run parse-definitions
  reporter:
    build: .
    image: drae-getter
    volumes:
      - ./playwright-report:/app/playwright-report
    ports:
      - 80:9323
    command: npm run show-report
