version: '3.0'

services:
  getter:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    command: npm run scrap
  reporter:
    build: .
    image: drae-getter
    volumes:
      - ./playwright-report:/app/playwright-report
    ports:
      - 80:9323
    command: npm run show-report
