version: '3.0'

services:
  getter:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run scrap
  definitions-1:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run scrap-definitions -- --shard=1/3
  definitions-2:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run scrap-definitions -- --shard=2/3
  definitions-3:
    build: .
    image: drae-getter
    volumes:
      - ./cache:/app/cache
      - ./scrap:/app/scrap
      - ./playwright-report:/app/playwright-report
    environment:
      - CI=1
    command: npm run scrap-definitions -- --shard=3/3
  reporter:
    build: .
    image: drae-getter
    volumes:
      - ./playwright-report:/app/playwright-report
    ports:
      - 80:9323
    command: npm run show-report
